from clases import Stack, Queue, OrderedTable

print("PRUEBA STACK")
stack = Stack()
stack.push(10)
stack.push(20)
stack.push(30)
print("Stack: ", stack.show_stack())
print("Peek: ", stack.peek())
print("Pop: ", stack.pop())
print("Stack:", stack.show_stack())
print("\n")

print("PRUEBA QUEUE")
queue = Queue()
queue.enqueue("A")
queue.enqueue("B")
queue.enqueue("C")
print("Queue: ", queue.show_queue())
print("Front: ", queue.front())
print("Dequeue: ", queue.dequeue())
print("Queue:", queue.show_queue())
print("\n")

print("PRUEBA ORDER")
table = OrderedTable()
table.set("Juan", 32)
table.set("Ana", 21)
table.set("Pedro",73)
table.set("Maria", 14)
print("Items: ", table.items())
print("Size: ", table.size())
print("Keys: ", table.keys())
print("Get Pedro: ", table.get("Pedro"))
print("Delete Maria: ", table.delete("Maria"))
print ("Items: ", table.items())
table.set("Ana", 26)
table.set("Zoe", 10)
print("Items: ", table.items())